export type Difficulty = 'EASY' | 'MEDIUM' | 'HARD';

export interface PatternQuestion {
  id: number;
  type: 'color' | 'shape' | 'emoji' | 'number' | 'size' | 'rotation' | 'mixed';
  sequence: string[];
  missingIndex: number;
  answer: string;
  options: string[];
  difficulty: Difficulty;
}

export const PATTERN_QUESTIONS: PatternQuestion[] = [
  // ── EASY: 2-item AB repeating ──────────────────────────────────
  { id: 1, difficulty: 'EASY', type: 'color',
    sequence: ['🔴', '🔵', '🔴', '🔵', '?', '🔵'],
    missingIndex: 4, answer: '🔴', options: ['🔴', '🔵', '🟡'] },
  { id: 2, difficulty: 'EASY', type: 'color',
    sequence: ['🟡', '🟢', '🟡', '🟢', '🟡', '?'],
    missingIndex: 5, answer: '🟢', options: ['🟡', '🟢', '🔴'] },
  { id: 3, difficulty: 'EASY', type: 'color',
    sequence: ['🟠', '🟣', '🟠', '🟣', '?', '🟣'],
    missingIndex: 4, answer: '🟠', options: ['🟠', '🟣', '🟢'] },
  { id: 4, difficulty: 'EASY', type: 'shape',
    sequence: ['⭕', '🔺', '⭕', '🔺', '?', '🔺'],
    missingIndex: 4, answer: '⭕', options: ['⭕', '🔺', '⬛'] },
  { id: 5, difficulty: 'EASY', type: 'shape',
    sequence: ['⬛', '⬜', '⬛', '⬜', '⬛', '?'],
    missingIndex: 5, answer: '⬜', options: ['⬛', '⬜', '🔺'] },
  { id: 6, difficulty: 'EASY', type: 'emoji',
    sequence: ['🐱', '🐶', '🐱', '🐶', '?', '🐶'],
    missingIndex: 4, answer: '🐱', options: ['🐱', '🐶', '🐸'] },
  { id: 7, difficulty: 'EASY', type: 'emoji',
    sequence: ['🌟', '🌙', '🌟', '🌙', '🌟', '?'],
    missingIndex: 5, answer: '🌙', options: ['🌟', '🌙', '☀️'] },
  { id: 8, difficulty: 'EASY', type: 'emoji',
    sequence: ['🚗', '✈️', '🚗', '✈️', '?', '✈️'],
    missingIndex: 4, answer: '🚗', options: ['🚗', '✈️', '🚢'] },
  { id: 9, difficulty: 'EASY', type: 'emoji',
    sequence: ['🦁', '🐘', '🦁', '🐘', '🦁', '?'],
    missingIndex: 5, answer: '🐘', options: ['🦁', '🐘', '🦒'] },
  { id: 10, difficulty: 'EASY', type: 'emoji',
    sequence: ['🍎', '🍊', '🍎', '🍊', '?', '🍊'],
    missingIndex: 4, answer: '🍎', options: ['🍎', '🍊', '🍋'] },
  { id: 11, difficulty: 'EASY', type: 'emoji',
    sequence: ['🌺', '🌻', '🌺', '🌻', '🌺', '?'],
    missingIndex: 5, answer: '🌻', options: ['🌺', '🌻', '🌹'] },
  { id: 12, difficulty: 'EASY', type: 'size',
    sequence: ['🔵', '🔹', '🔵', '🔹', '?', '🔹'],
    missingIndex: 4, answer: '🔵', options: ['🔵', '🔹', '🟦'] },
  { id: 13, difficulty: 'EASY', type: 'size',
    sequence: ['🟡', '🔸', '🟡', '🔸', '🟡', '?'],
    missingIndex: 5, answer: '🔸', options: ['🟡', '🔸', '🟠'] },
  { id: 14, difficulty: 'EASY', type: 'emoji',
    sequence: ['🐝', '🦋', '🐝', '🦋', '?', '🦋'],
    missingIndex: 4, answer: '🐝', options: ['🐝', '🦋', '🐛'] },
  { id: 15, difficulty: 'EASY', type: 'emoji',
    sequence: ['🍕', '🍔', '🍕', '🍔', '🍕', '?'],
    missingIndex: 5, answer: '🍔', options: ['🍕', '🍔', '🌮'] },

  // ── MEDIUM: 3-item ABC or growing by 1 ─────────────────────────
  { id: 16, difficulty: 'MEDIUM', type: 'emoji',
    sequence: ['🍎', '🍊', '🍋', '🍎', '🍊', '?'],
    missingIndex: 5, answer: '🍋', options: ['🍎', '🍊', '🍋'] },
  { id: 17, difficulty: 'MEDIUM', type: 'color',
    sequence: ['🔴', '🟡', '🔵', '🔴', '🟡', '?'],
    missingIndex: 5, answer: '🔵', options: ['🔴', '🟡', '🔵'] },
  { id: 18, difficulty: 'MEDIUM', type: 'shape',
    sequence: ['🔺', '⭕', '⬛', '🔺', '⭕', '?'],
    missingIndex: 5, answer: '⬛', options: ['🔺', '⭕', '⬛'] },
  { id: 19, difficulty: 'MEDIUM', type: 'emoji',
    sequence: ['🐮', '🐷', '🐔', '🐮', '?', '🐔'],
    missingIndex: 4, answer: '🐷', options: ['🐮', '🐷', '🐔'] },
  { id: 20, difficulty: 'MEDIUM', type: 'emoji',
    sequence: ['⭐', '⭐', '🌙', '⭐', '⭐', '?'],
    missingIndex: 5, answer: '🌙', options: ['⭐', '🌙', '☀️'] },
  { id: 21, difficulty: 'MEDIUM', type: 'emoji',
    sequence: ['🐸', '🐸', '🦊', '🐸', '?', '🦊'],
    missingIndex: 4, answer: '🐸', options: ['🐸', '🦊', '🦁'] },
  { id: 22, difficulty: 'MEDIUM', type: 'number',
    sequence: ['1', '2', '3', '?'],
    missingIndex: 3, answer: '4', options: ['4', '5', '6'] },
  { id: 23, difficulty: 'MEDIUM', type: 'number',
    sequence: ['2', '4', '6', '?'],
    missingIndex: 3, answer: '8', options: ['7', '8', '9'] },
  { id: 24, difficulty: 'MEDIUM', type: 'number',
    sequence: ['10', '9', '8', '?'],
    missingIndex: 3, answer: '7', options: ['6', '7', '5'] },
  { id: 25, difficulty: 'MEDIUM', type: 'number',
    sequence: ['5', '10', '15', '?'],
    missingIndex: 3, answer: '20', options: ['18', '20', '25'] },
  { id: 26, difficulty: 'MEDIUM', type: 'rotation',
    sequence: ['⬆️', '➡️', '⬇️', '⬅️', '⬆️', '?'],
    missingIndex: 5, answer: '➡️', options: ['⬆️', '➡️', '⬇️'] },
  { id: 27, difficulty: 'MEDIUM', type: 'rotation',
    sequence: ['⬆️', '➡️', '⬆️', '➡️', '?', '➡️'],
    missingIndex: 4, answer: '⬆️', options: ['⬆️', '➡️', '⬇️'] },
  { id: 28, difficulty: 'MEDIUM', type: 'mixed',
    sequence: ['🔴🐱', '🔵🐶', '🔴🐱', '🔵🐶', '?', '🔵🐶'],
    missingIndex: 4, answer: '🔴🐱', options: ['🔴🐱', '🔵🐶', '🟡🐸'] },
  { id: 29, difficulty: 'MEDIUM', type: 'emoji',
    sequence: ['🌈', '☁️', '🌈', '☁️', '🌈', '?'],
    missingIndex: 5, answer: '☁️', options: ['🌈', '☁️', '⛅'] },
  { id: 30, difficulty: 'MEDIUM', type: 'shape',
    sequence: ['💎', '⬛', '💎', '⬛', '?', '⬛'],
    missingIndex: 4, answer: '💎', options: ['💎', '⬛', '⭕'] },

  // ── HARD: number sequences, ×2, +3 ─────────────────────────────
  { id: 31, difficulty: 'HARD', type: 'number',
    sequence: ['1', '2', '4', '8', '?'],
    missingIndex: 4, answer: '16', options: ['12', '16', '20', '10'] },
  { id: 32, difficulty: 'HARD', type: 'number',
    sequence: ['1', '3', '5', '?'],
    missingIndex: 3, answer: '7', options: ['6', '7', '8', '9'] },
  { id: 33, difficulty: 'HARD', type: 'number',
    sequence: ['3', '6', '9', '?'],
    missingIndex: 3, answer: '12', options: ['10', '11', '12', '13'] },
  { id: 34, difficulty: 'HARD', type: 'number',
    sequence: ['100', '90', '80', '?'],
    missingIndex: 3, answer: '70', options: ['60', '70', '75', '50'] },
  { id: 35, difficulty: 'HARD', type: 'number',
    sequence: ['2', '4', '8', '16', '?'],
    missingIndex: 4, answer: '32', options: ['24', '30', '32', '20'] },
  { id: 36, difficulty: 'HARD', type: 'number',
    sequence: ['1', '4', '9', '16', '?'],
    missingIndex: 4, answer: '25', options: ['20', '24', '25', '36'] },
  { id: 37, difficulty: 'HARD', type: 'number',
    sequence: ['2', '2', '4', '?'],
    missingIndex: 3, answer: '4', options: ['3', '4', '6', '8'] },
  { id: 38, difficulty: 'HARD', type: 'mixed',
    sequence: ['🔴⭐', '🔴⭐', '🔵⭐', '🔴⭐', '🔴⭐', '?'],
    missingIndex: 5, answer: '🔵⭐', options: ['🔴⭐', '🔵⭐', '🟡⭐', '🔴🌙'] },
  { id: 39, difficulty: 'HARD', type: 'rotation',
    sequence: ['⬆️', '➡️', '⬇️', '⬅️', '?', '➡️'],
    missingIndex: 4, answer: '⬆️', options: ['⬆️', '⬇️', '⬅️', '➡️'] },
  { id: 40, difficulty: 'HARD', type: 'number',
    sequence: ['5', '8', '11', '?'],
    missingIndex: 3, answer: '14', options: ['13', '14', '15', '16'] },
  { id: 41, difficulty: 'HARD', type: 'number',
    sequence: ['1', '1', '2', '3', '5', '?'],
    missingIndex: 5, answer: '8', options: ['6', '7', '8', '9'] },
  { id: 42, difficulty: 'HARD', type: 'number',
    sequence: ['50', '45', '40', '?'],
    missingIndex: 3, answer: '35', options: ['30', '35', '38', '33'] },
];

export const PATTERN_EMOJIS_POOL = [
  '🔴', '🔵', '🟡', '🟢', '🟠', '🟣',
  '⭕', '🔺', '⬛', '⬜', '💎',
  '🐱', '🐶', '🐸', '🦊', '🦁', '🐘',
  '🍎', '🍊', '🍋', '🌟', '🌙', '☀️',
];
